# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hunl_main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(310, 242)
        main.setFocusPolicy(QtCore.Qt.ClickFocus)
        main.setToolTip("")
        main.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.hvr_btn = QtWidgets.QPushButton(self.centralwidget)
        self.hvr_btn.setGeometry(QtCore.QRect(34, 93, 121, 32))
        self.hvr_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.hvr_btn.setObjectName("hvr_btn")
        self.rvr_btn = QtWidgets.QPushButton(self.centralwidget)
        self.rvr_btn.setGeometry(QtCore.QRect(159, 93, 121, 32))
        self.rvr_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rvr_btn.setObjectName("rvr_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 13, 261, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(43, 70, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(43, 147, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.tb_btn = QtWidgets.QPushButton(self.centralwidget)
        self.tb_btn.setGeometry(QtCore.QRect(34, 170, 121, 32))
        self.tb_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tb_btn.setObjectName("tb_btn")
        self.fp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fp_btn.setGeometry(QtCore.QRect(159, 170, 121, 32))
        self.fp_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fp_btn.setObjectName("fp_btn")
        main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.actionTest = QtWidgets.QAction(main)
        self.actionTest.setObjectName("actionTest")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "HH Poker Tools"))
        self.hvr_btn.setStatusTip(_translate("main", "Equity: Hand versus Range"))
        self.hvr_btn.setText(_translate("main", "Hand v Range"))
        self.rvr_btn.setStatusTip(_translate("main", "Equity: Range versus Range"))
        self.rvr_btn.setText(_translate("main", "Range vs Range"))
        self.label.setText(_translate("main", "HH Poker Tools"))
        self.label_2.setText(_translate("main", "Equity Calculators"))
        self.label_3.setText(_translate("main", "Solver Functions"))
        self.tb_btn.setStatusTip(_translate("main", "Equity: Tree Builder"))
        self.tb_btn.setText(_translate("main", "Tree Builder"))
        self.fp_btn.setStatusTip(_translate("main", "Equity: Fictitious Play"))
        self.fp_btn.setText(_translate("main", "Fictitious Play"))
        self.actionTest.setText(_translate("main", "test"))

